//! Focused behavior tests for the adjacent implementation.

include!("behavior_01_runtime_tab_control_row_uses_exact_half_open_boundaries.rs");
include!("behavior_02_returning_to_the_applied_tab_skips_native_visibility_and_focus_work.rs");
include!("behavior_03_runtime_navigation_session_and_platform_contracts.rs");
include!("behavior_04_native_launch_errors_keep_their_code_and_message_in_diagnostics.rs");
include!("behavior_05_input_dispatch_compensation_is_net_state_and_submission_is_tristate.rs");
include!("behavior_06_navigation_input_tickets_require_latest_epoch_drain_and_page_finish.rs");
include!("behavior_07_windows_reparent_sync_uses_one_bounded_deadline.rs");
include!("behavior_08_native_presentation_contract_is_platform_neutral.rs");
include!("behavior_09_native_operation_contract_is_shared.rs");
include!("behavior_10_failed_launch_cleanup_is_idempotent.rs");
include!("behavior_11_runtime_diagnostics_are_bounded_and_classified.rs");
include!("behavior_12_geometry_reload_and_shutdown_contracts.rs");
include!("behavior_13_macro_key_guard_is_fail_closed_for_keydown.rs");
include!("behavior_14_native_operation_registry_is_bounded_and_terminal.rs");
include!("behavior_15_window_close_transaction_is_generation_fenced.rs");
include!("behavior_16_focus_broker_is_global_and_generation_fenced.rs");
include!("behavior_17_main_window_actor_is_ordered_and_revisioned.rs");
include!("behavior_18_display_topology_transaction_is_atomic.rs");
include!("behavior_19_tab_drag_transaction_is_terminal.rs");
include!("behavior_20_surface_recovery_is_generation_fenced.rs");
include!("behavior_21_power_lifecycle_is_epoch_fenced.rs");
include!("behavior_22_tab_activation_transaction_converges.rs");
include!("behavior_23_tab_chrome_projection_is_instance_fenced.rs");
include!("behavior_24_tab_mutation_projection_is_frozen.rs");
include!("behavior_25_provisional_launch_attempts_are_identity_fenced.rs");
include!("behavior_26_tab_drag_intent_is_latest.rs");
include!("behavior_27_drag_cursor_and_close_relaunch_are_generation_fenced.rs");
