[package]
name = "rion-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = []
system-webview-probe = ["rion-platform/system-webview-probe"]

[dependencies]
base64.workspace = true
chrono.workspace = true
crossbeam-channel.workspace = true
fs2.workspace = true
getrandom.workspace = true
regex.workspace = true
reqwest.workspace = true
rion-platform = { path = "../rion-platform", default-features = false }
rusqlite.workspace = true
rusty-leveldb.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile = "3.24.0"
thiserror.workspace = true
tokio.workspace = true
ts-rs.workspace = true
url.workspace = true
uuid.workspace = true
