export const desktopE2eSpecByPhase: Readonly<Record<string, string>> = {
  "chromium-app-crud-cleanup": "e2e/desktop/specs/chromium-app-crud.e2e.ts",
  "chromium-app-crud-final-restart": "e2e/desktop/specs/chromium-app-crud.e2e.ts",
  "chromium-app-crud-mutations": "e2e/desktop/specs/chromium-app-crud.e2e.ts",
  "chromium-app-recovery-seed": "e2e/desktop/specs/chromium-app-recovery.e2e.ts",
  "chromium-app-recovery-force": "e2e/desktop/specs/chromium-app-recovery.e2e.ts",
  "chromium-app-recovery-restore": "e2e/desktop/specs/chromium-app-recovery.e2e.ts",
  "chromium-mixed-recovery-seed": "e2e/desktop/specs/chromium-mixed-recovery.e2e.ts",
  "chromium-mixed-recovery-force": "e2e/desktop/specs/chromium-mixed-recovery.e2e.ts",
  "chromium-mixed-recovery-restore": "e2e/desktop/specs/chromium-mixed-recovery.e2e.ts",
  "chromium-window-recovery-seed": "e2e/desktop/specs/chromium-window-recovery-ui.e2e.ts",
  "chromium-window-recovery-force": "e2e/desktop/specs/chromium-window-recovery-ui.e2e.ts",
  "chromium-window-recovery-restore-force": "e2e/desktop/specs/chromium-window-recovery-ui.e2e.ts",
  "chromium-window-recovery-discard": "e2e/desktop/specs/chromium-window-recovery-ui.e2e.ts",
  "chromium-window-recovery-final-show": "e2e/desktop/specs/chromium-window-recovery-ui.e2e.ts",
  "chromium-shell-smoke": "e2e/desktop/specs/chromium-shell.e2e.ts",
  "chromium-game-crud-restart": "e2e/desktop/specs/chromium-game-crud.e2e.ts",
  "chromium-game-crud-seed": "e2e/desktop/specs/chromium-game-crud.e2e.ts",
  "chromium-game-window-ui-restart": "e2e/desktop/specs/chromium-game-window-ui.e2e.ts",
  "chromium-game-window-ui-seed": "e2e/desktop/specs/chromium-game-window-ui.e2e.ts",
  "chromium-fullscreen-toolbar-restart": "e2e/desktop/specs/chromium-fullscreen-toolbar.e2e.ts",
  "chromium-fullscreen-toolbar-seed": "e2e/desktop/specs/chromium-fullscreen-toolbar.e2e.ts",
  "chromium-macro-ui-restart": "e2e/desktop/specs/chromium-macro-ui.e2e.ts",
  "chromium-macro-ui-seed": "e2e/desktop/specs/chromium-macro-ui.e2e.ts",
  "chromium-macro-native-effect": "e2e/desktop/specs/chromium-macro-native-effect.e2e.ts",
  "chromium-macro-background-tab":
    "e2e/desktop/specs/chromium-macro-background-tab.e2e.ts",
  "chromium-controlled-role-reload":
    "e2e/desktop/specs/chromium-controlled-role-reload.e2e.ts",
  "chromium-macro-standby-recovery":
    "e2e/desktop/specs/chromium-macro-standby-recovery.e2e.ts",
  "chromium-macro-cutover-input-recovery":
    "e2e/desktop/specs/chromium-macro-cutover.e2e.ts",
  "chromium-macro-cutover-keyboard":
    "e2e/desktop/specs/chromium-macro-cutover.e2e.ts",
  "chromium-macro-cutover-terminal-cleanup-restart":
    "e2e/desktop/specs/chromium-macro-cutover.e2e.ts",
  "chromium-macro-cutover-terminal-cleanup-seed":
    "e2e/desktop/specs/chromium-macro-cutover.e2e.ts",
  "chromium-macro-cutover-topology-restart":
    "e2e/desktop/specs/chromium-macro-cutover.e2e.ts",
  "chromium-macro-cutover-topology-seed":
    "e2e/desktop/specs/chromium-macro-cutover.e2e.ts",
  "chromium-entity-persistence-restart": "e2e/desktop/specs/chromium-entity-persistence.e2e.ts",
  "chromium-entity-persistence-seed": "e2e/desktop/specs/chromium-entity-persistence.e2e.ts",
  "chromium-role-session-reset-restart": "e2e/desktop/specs/chromium-role-session-reset.e2e.ts",
  "chromium-role-session-reset-seed": "e2e/desktop/specs/chromium-role-session-reset.e2e.ts",
  "chromium-role-session-isolation-restart": "e2e/desktop/specs/chromium-role-session-isolation.e2e.ts",
  "chromium-role-session-isolation-seed": "e2e/desktop/specs/chromium-role-session-isolation.e2e.ts",
  "chromium-settings-persistence-restart": "e2e/desktop/specs/chromium-settings-persistence.e2e.ts",
  "chromium-settings-persistence-seed": "e2e/desktop/specs/chromium-settings-persistence.e2e.ts",
  "chromium-workspace-web-slot-restart": "e2e/desktop/specs/chromium-workspace-web-slot.e2e.ts",
  "chromium-workspace-web-slot-seed": "e2e/desktop/specs/chromium-workspace-web-slot.e2e.ts",
  "chromium-workspace-web-fullscreen-restart": "e2e/desktop/specs/chromium-workspace-web-fullscreen.e2e.ts",
  "chromium-workspace-web-fullscreen-seed": "e2e/desktop/specs/chromium-workspace-web-fullscreen.e2e.ts",
  "chromium-workspace-web-only-restart": "e2e/desktop/specs/chromium-workspace-web-only.e2e.ts",
  "chromium-workspace-web-only-seed": "e2e/desktop/specs/chromium-workspace-web-only.e2e.ts",
  "chromium-workspace-shared-role": "e2e/desktop/specs/chromium-workspace-shared-role.e2e.ts",
  "chromium-workspaces-recovery": "e2e/desktop/specs/chromium-workspaces-recovery.e2e.ts",
  "chromium-quit-guard-restart": "e2e/desktop/specs/chromium-quit-guard.e2e.ts",
  "chromium-quit-guard-seed": "e2e/desktop/specs/chromium-quit-guard.e2e.ts",
  "chromium-quick-access-restart": "e2e/desktop/specs/chromium-quick-access.e2e.ts",
  "chromium-quick-access-seed": "e2e/desktop/specs/chromium-quick-access.e2e.ts",
  "chromium-system-settings": "e2e/desktop/specs/chromium-system-settings.e2e.ts",
  "chromium-tabs-visible-restart": "e2e/desktop/specs/chromium-tabs-parity.e2e.ts",
  "chromium-tabs-visible-seed": "e2e/desktop/specs/chromium-tabs-parity.e2e.ts",
  "chromium-native-window-display-extended":
    "e2e/desktop/specs/chromium-native-window-display.e2e.ts",
  "chromium-windows-trusted-input-physical": "e2e/desktop/specs/chromium-windows-trusted-input-physical.e2e.ts",
  "crash-discard": "e2e/desktop/specs/game-window-lifecycle.e2e.ts",
  "crash-restart": "e2e/desktop/specs/game-window-lifecycle.e2e.ts",
  "extended-native": "e2e/desktop/specs/extended-native.e2e.ts",
  "force-terminate": "e2e/desktop/specs/game-window-lifecycle.e2e.ts",
  "fullscreen-toolbar": "e2e/desktop/specs/app-journeys.e2e.ts",
  "fullscreen-toolbar-restart": "e2e/desktop/specs/app-journeys.e2e.ts",
  "p0-macro-background-tab": "e2e/desktop/specs/macro-runtime.e2e.ts",
  "p0-macro-keyboard-lifecycle": "e2e/desktop/specs/macro-runtime.e2e.ts",
  "p0-macro-middle-button": "e2e/desktop/specs/macro-runtime.e2e.ts",
  "p0-macro-native-effect": "e2e/desktop/specs/macro-runtime.e2e.ts",
  "p0-macro-terminal-cleanup": "e2e/desktop/specs/tab-cleanup.e2e.ts",
  "p0-tabs-visible-activation": "e2e/desktop/specs/tab-cleanup.e2e.ts",
  "p1-final-restart": "e2e/desktop/specs/full-desktop.e2e.ts",
  "p1-guard-cleanup": "e2e/desktop/specs/full-desktop.e2e.ts",
  "p1-mutations": "e2e/desktop/specs/full-desktop.e2e.ts",
  "p1-macro-multirole": "e2e/desktop/specs/macro-runtime.e2e.ts",
  "p1-macro-input-recovery": "e2e/desktop/specs/macro-runtime.e2e.ts",
  "p1-macro-standby-recovery": "e2e/desktop/specs/macro-runtime.e2e.ts",
  "p1-role-session-isolation": "e2e/desktop/specs/role-isolation.e2e.ts",
  "p1-role-session-seed": "e2e/desktop/specs/role-isolation.e2e.ts",
  "p1-workspace-shared-role": "e2e/desktop/specs/role-isolation.e2e.ts",
  "p1-workspace-recovery": "e2e/desktop/specs/workspace-recovery.e2e.ts",
  "p1-cross-domain-seed": "e2e/desktop/specs/cross-domain-runtime.e2e.ts",
  "p1-cross-domain-topology-force": "e2e/desktop/specs/cross-domain-runtime.e2e.ts",
  "p1-cross-domain-recovery": "e2e/desktop/specs/cross-domain-runtime.e2e.ts",
  "p1-cross-domain-final-restart": "e2e/desktop/specs/cross-domain-runtime.e2e.ts",
  "recovery-final-restart": "e2e/desktop/specs/game-window-lifecycle.e2e.ts",
  restart: "e2e/desktop/specs/game-window-lifecycle.e2e.ts",
  seed: "e2e/desktop/specs/game-window-lifecycle.e2e.ts",
  "smoke-restart": "e2e/desktop/specs/app-journeys.e2e.ts",
  "smoke-seed": "e2e/desktop/specs/app-journeys.e2e.ts",
  "system-settings": "e2e/desktop/specs/system-settings.e2e.ts",
  "workspace-contained-fullscreen": "e2e/desktop/specs/app-journeys.e2e.ts"
};

export function desktopE2eSpecForPhase(phase: string): string {
  const spec = desktopE2eSpecByPhase[phase];
  if (!spec) throw new Error(`Unknown desktop E2E phase: ${phase}`);
  return spec;
}
