import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = new URL("../", import.meta.url);
const escape = (value) => value.replaceAll("&", "&amp;").replaceAll('"', "&quot;").replaceAll("<", "&lt;").replaceAll(">", "&gt;");
const languages = ["en", "zh-TW", "zh-CN", "ja"];

export function buildWorkspaceStartPage(root = new URL("../", import.meta.url)) {
  const read = (path) => readFileSync(new URL(path, root), "utf8");
  const catalog = JSON.parse(read("src/shared/workspaceWebCatalog.json"));
  const translations = Object.fromEntries(languages.map((language) => [language,
    JSON.parse(read(`src/renderer/src/i18n/${language}.json`))]));
  const translated = (key) => languages.map((language) =>
    `<span data-language="${language}">${escape(translations[language][key])}</span>`).join("");
  const cards = catalog.map((site) => {
    const mime = site.brandAsset.endsWith("svg") ? "image/svg+xml" : site.brandAsset.endsWith("png") ? "image/png" : "image/jpeg";
    const image = readFileSync(new URL(`src/renderer/src/assets/workspace-web/${site.brandAsset}`, root)).toString("base64");
    const domain = new URL(site.startUrl).hostname.replace(/^www\./u, "");
    return `<a class="site" data-workspace-start-site="${site.id}" href="${escape(site.startUrl)}" target="_self"><img class="brand${site.brandImagePresentation === "cover" ? " cover" : ""}" alt="" width="40" height="40" src="data:${mime};base64,${image}"><span><span class="name">${escape(site.name)}</span><span class="domain">${escape(domain)}</span></span></a>`;
  }).join("\n");
  return `<!doctype html>\n<!-- Generated by scripts/generateWorkspaceStartPage.mjs. Do not edit. -->
<html lang="en" data-theme="light"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; img-src data:; base-uri 'none'; form-action 'none'">
<title>Rion Studio</title><style>${read("src/shared/designTokens.css")}\n${read("src/renderer/runtime-workspace-start.css")}</style></head>
<body data-rion-workspace-start><main><header><span class="eyebrow">RION STUDIO</span><h1 id="website-title">${translated("workspaces.webStartTitle")}</h1><p class="hint">${translated("workspaces.webStartHint")}</p></header><nav class="sites" aria-labelledby="website-title">${cards}</nav></main></body></html>\n`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(new URL("src/shared/generated/workspace-start.html", root), buildWorkspaceStartPage());
}
