mod app;
mod bootstrap_settings;
mod browser_action_effects;
mod browser_operations;
mod browser_runtime;
mod chrome_profile_import;
mod compatibility_runtime;
mod data_root_migration;
mod database;
mod diagnostics;
mod domain;
mod embedded_input;
mod engine_resolution;
mod error;
mod graphics_diagnostics;
mod layout;
mod legal;
mod log_capture;
mod macro_graph;
mod macro_runtime;
mod model;
pub mod operation_actor;
mod overlay;
mod portable;
mod role_browser_data;
mod runtime_sequence;
mod scheduler;
mod session_import;
mod system_fonts;
mod telemetry;
mod windows_graphics_events;

#[cfg(test)]
macro_rules! v1_case {
    ($id:expr, $assertions:block) => {{
        let v1_case_id: &str = $id;
        assert!(
            !v1_case_id.is_empty(),
            "v1 parity case identifiers must not be empty"
        );
        $assertions
    }};
}

#[cfg(test)]
pub(crate) use v1_case;

pub use app::AppCore;
pub use bootstrap_settings::read_plan as read_bootstrap_plan;
pub use data_root_migration::{DataRootMigrationOutcome, migrate_legacy_data_root};
pub use error::{CoreError, CoreErrorPayload, CoreResult};
pub use legal::current_versions as current_legal_document_versions;
pub use model::{
    AppCoreOptions, ApplicationDiagnosticsSnapshotRecord, BootstrapPlanRecord, BrowserAction,
    BrowserActionRequest, BrowserActionResult, BrowserEngineResolutionRecord,
    BrowserFontSettingsRecord, BrowserGraphicsBackendSettingsRecord, BrowserGraphicsSettingsRecord,
    BrowserHostKind, BrowserOperationLease, BrowserOperationRequest, BrowserRoleStatusRecord,
    BrowserRuntimeCommand, BrowserRuntimeResult, BrowserRuntimeRoleRecord, BrowserRuntimeSnapshot,
    BrowserRuntimeTabRecord, BrowserRuntimeWindowRecord, BrowserRuntimeWorkspaceRecord,
    BrowserWorkspaceStatusRecord, BulkDeleteResultRecord, BulkDeleteSkippedItemRecord,
    ChromeProfileEntryRecord, ChromeProfileImportAuthStateRecord,
    ChromeProfileImportItemResultRecord, ChromeProfileImportPreviewRecord,
    ChromeProfileImportProgressRecord, ChromeProfileImportResolutionRecord,
    ChromeProfileImportResultRecord, ChromeProfileImportUnsupportedCountsRecord,
    ChromiumSwitchRecord, CompatibilityCheckOutcome, CompatibilityCheckPlanRecord,
    CompatibilityRunPhase, CompatibilityRunStatusRecord, CoreCommand, CoreEffectAction,
    CoreEffectDispatchReport, CoreEffectMetricsRecord, CoreEffectRequest, CoreEffectResult,
    CoreEffectTarget, CoreEffectTargetKind, CoreEvent, CoreStateSnapshotRecord,
    CountedLatencySummaryRecord, DiagnosticDisplayRecord, DiagnosticExportResultRecord,
    DisplayFingerprintRecord, DisplayInfoRecord, DisplayTargetRecord, EmbeddedKeyEffectRecord,
    EmbeddedKeyTransitionRecord, EmbeddedLaunchResultRecord, EmbeddedLaunchTargetRecord,
    EmbeddedRoleLoadEffectRecord, EmbeddedRoleViewEffectRecord, EmbeddedTabEffectRecord,
    EngineCapabilitySnapshotRecord, EngineCapabilityStatus, EngineCompatibilityCacheKeyRecord,
    EngineCompatibilityCacheRecord, GameBrowserSettingsRecord, GameCreateInputRecord,
    GameCreateRequest, GameUpdateInputRecord, GameUpdateRequest, GameWindowCreateInputRecord,
    GameWindowPlacementRecord, GameWindowRoleViewRecord, GameWindowTabRecord,
    GameWindowUpdateInputRecord, GraphicsDeviceDiagnosticsRecord, GraphicsDiagnosticsRecord,
    LatencySummaryRecord, LayoutBounds, LayoutDividerBounds, LayoutDividerInput, LayoutRect,
    LayoutRoleBounds, LayoutRoleInput, LegacySessionRestoreRecord, LegalAcceptDocumentsInputRecord,
    LegalAcceptanceRecord, LegalAcceptanceStatusRecord, LegalDocumentVersionsRecord,
    LocalStorageEntryRecord, LocalStorageSyncRoleEffectRecord, LocalStorageSyncSourceEffectRecord,
    LogCaptureRecord, LogEntry, LogErrorDetails, LogLevel, LogPageRecord, LogQuery, LogSource,
    LogStorageStatusRecord, MacroBadgePositionRecord, MacroCoordinateRecord,
    MacroCreateInputRecord, MacroCreateRequest, MacroDefinition, MacroInvocationRequest,
    MacroLastClick, MacroOverlayRequestRecord, MacroOverlayStartSummaryRecord,
    MacroOverlayViewModelRecord, MacroPressInvocationRequest, MacroPressRequest,
    MacroReleaseRequest, MacroRepeat, MacroRunStatus, MacroRuntimeSettings, MacroSettingsRecord,
    MacroStartRequest, MacroStepDefinition, MacroStepInputRecord, MacroTrigger,
    MacroUpdateInputRecord, MacroUpdateRequest, OperationCancelResultRecord,
    PerformanceTelemetryRecord, PortableDataRecord, PortableDataSelectionRecord,
    PortableExportResultRecord, PortableGameRecord, PortableGameWindowRecord,
    PortableImportOperationSummaryRecord, PortableImportOperationsRecord,
    PortableImportPreviewRecord, PortableImportResultRecord, PortableImportWarningRecord,
    PortableLaunchWorkspaceRecord, PortableMacroConflictCandidateRecord,
    PortableMacroConflictRecord, PortableMacroConflictResolutionRecord, PortableMacroRecord,
    PortablePreferencesRecord, PortableRoleRecord, ResolvedBrowserEngine, RoleCreateInputRecord,
    RoleCreateRequest, RoleGameAssignmentRecord, RolePathsRecord, RoleUpdateInputRecord,
    RoleUpdateRequest, RuntimeRestoreSessionRecord, RuntimeRestoreTabRecord,
    RuntimeRestoreWindowRecord, RuntimeVersionRecord, RuntimeWindowPreferencesRecord,
    SessionCookieRecord, SessionTransferPayloadRecord, StateCollection,
    StateCompatibilityLoadRecord, StateCompatibilityObservationsRecord,
    StateCompatibilityRecommendationRecord, StateCompatibilityReportRecord, StateGameRecord,
    StateGameWindowRecord, StateLaunchWorkspaceRecord, StateMacroRecord, StateNormalizedRectRecord,
    StatePixelBoundsRecord, StateResolutionRecord, StateRoleRecord, StateWebGraphicsRecord,
    StateWorkspaceSlotRecord, SystemFontFamilyRecord, SystemWebViewIssueReason,
    SystemWebViewProbeRecord, SystemWebViewRuntimeRegistrationRecord, TelemetryMetric,
    TelemetrySampleRecord, WindowsGraphicsEventCollectionRecord, WindowsGraphicsEventRecord,
    WorkspaceAppearanceSettingsRecord, WorkspaceCreateInputRecord, WorkspaceCreateRequest,
    WorkspaceDividerDescriptor, WorkspaceDividerResizeInput, WorkspaceDividerResizeOutput,
    WorkspaceLayoutInput, WorkspaceLayoutOutput, WorkspaceSlotInputRecord, WorkspaceSlotRequest,
    WorkspaceUpdateInputRecord, WorkspaceUpdateRequest,
};

pub const CORE_VERSION: &str = env!("CARGO_PKG_VERSION");

#[cfg(test)]
mod generated_contract_tests {
    use std::{fs, path::PathBuf};

    #[test]
    fn export_bindings_index() {
        let path =
            PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../src/shared/generated/index.ts");
        fs::write(
            path,
            concat!(
                "// Generated by ts-rs from crates/rion-core. Do not edit exported type files by hand.\n",
                "export type { BrowserActionRequest } from \"./BrowserActionRequest\";\n",
                "export type { BrowserAction } from \"./BrowserAction\";\n",
                "export type { BrowserActionResult } from \"./BrowserActionResult\";\n",
                "export type { BrowserOperationLease } from \"./BrowserOperationLease\";\n",
                "export type { BrowserOperationRequest } from \"./BrowserOperationRequest\";\n",
                "export type { BrowserEngineResolutionRecord } from \"./BrowserEngineResolutionRecord\";\n",
                "export type { BrowserFontSettingsRecord } from \"./BrowserFontSettingsRecord\";\n",
                "export type { BrowserGraphicsBackendSettingsRecord } from \"./BrowserGraphicsBackendSettingsRecord\";\n",
                "export type { BrowserGraphicsSettingsRecord } from \"./BrowserGraphicsSettingsRecord\";\n",
                "export type { BrowserHostKind } from \"./BrowserHostKind\";\n",
                "export type { BrowserRoleStatusRecord } from \"./BrowserRoleStatusRecord\";\n",
                "export type { BrowserRuntimeCommand } from \"./BrowserRuntimeCommand\";\n",
                "export type { BrowserRuntimeWindowRecord } from \"./BrowserRuntimeWindowRecord\";\n",
                "export type { BrowserRuntimeResult } from \"./BrowserRuntimeResult\";\n",
                "export type { BrowserRuntimeRoleRecord } from \"./BrowserRuntimeRoleRecord\";\n",
                "export type { BrowserRuntimeSnapshot } from \"./BrowserRuntimeSnapshot\";\n",
                "export type { BrowserRuntimeTabRecord } from \"./BrowserRuntimeTabRecord\";\n",
                "export type { BrowserRuntimeWorkspaceRecord } from \"./BrowserRuntimeWorkspaceRecord\";\n",
                "export type { BrowserWorkspaceStatusRecord } from \"./BrowserWorkspaceStatusRecord\";\n",
                "export type { BootstrapPlanRecord } from \"./BootstrapPlanRecord\";\n",
                "export type { BulkDeleteResultRecord } from \"./BulkDeleteResultRecord\";\n",
                "export type { BulkDeleteSkippedItemRecord } from \"./BulkDeleteSkippedItemRecord\";\n",
                "export type { ChromeProfileEntryRecord } from \"./ChromeProfileEntryRecord\";\n",
                "export type { ChromeProfileImportAuthStateRecord } from \"./ChromeProfileImportAuthStateRecord\";\n",
                "export type { ChromeProfileImportItemResultRecord } from \"./ChromeProfileImportItemResultRecord\";\n",
                "export type { ChromeProfileImportPreviewRecord } from \"./ChromeProfileImportPreviewRecord\";\n",
                "export type { ChromeProfileImportProgressRecord } from \"./ChromeProfileImportProgressRecord\";\n",
                "export type { ChromeProfileImportResolutionRecord } from \"./ChromeProfileImportResolutionRecord\";\n",
                "export type { ChromeProfileImportResultRecord } from \"./ChromeProfileImportResultRecord\";\n",
                "export type { ChromeProfileImportUnsupportedCountsRecord } from \"./ChromeProfileImportUnsupportedCountsRecord\";\n",
                "export type { ChromiumSwitchRecord } from \"./ChromiumSwitchRecord\";\n",
                "export type { CompatibilityCheckOutcome } from \"./CompatibilityCheckOutcome\";\n",
                "export type { CompatibilityCheckPlanRecord } from \"./CompatibilityCheckPlanRecord\";\n",
                "export type { CompatibilityRunPhase } from \"./CompatibilityRunPhase\";\n",
                "export type { CompatibilityRunStatusRecord } from \"./CompatibilityRunStatusRecord\";\n",
                "export type { RuntimeVersionRecord } from \"./RuntimeVersionRecord\";\n",
                "export type { CoreErrorPayload } from \"./CoreErrorPayload\";\n",
                "export type { CoreCommand } from \"./CoreCommand\";\n",
                "export type { CoreCommandResult, CoreCommandResultMap, CoreJsonValue } from \"./CoreCommandResultMap\";\n",
                "export type { CoreEffectAction } from \"./CoreEffectAction\";\n",
                "export type { CoreEffectDispatchReport } from \"./CoreEffectDispatchReport\";\n",
                "export type { CoreEffectMetricsRecord } from \"./CoreEffectMetricsRecord\";\n",
                "export type { CoreEffectRequest } from \"./CoreEffectRequest\";\n",
                "export type { CoreEffectResult } from \"./CoreEffectResult\";\n",
                "export type { CoreEffectTarget } from \"./CoreEffectTarget\";\n",
                "export type { CoreEffectTargetKind } from \"./CoreEffectTargetKind\";\n",
                "export type { CoreEvent } from \"./CoreEvent\";\n",
                "export type { CoreStateSnapshotRecord } from \"./CoreStateSnapshotRecord\";\n",
                "export type { CountedLatencySummaryRecord } from \"./CountedLatencySummaryRecord\";\n",
                "export type { DiagnosticDisplayRecord } from \"./DiagnosticDisplayRecord\";\n",
                "export type { DiagnosticExportResultRecord } from \"./DiagnosticExportResultRecord\";\n",
                "export type { ApplicationDiagnosticsSnapshotRecord } from \"./ApplicationDiagnosticsSnapshotRecord\";\n",
                "export type { DisplayFingerprintRecord } from \"./DisplayFingerprintRecord\";\n",
                "export type { DisplayInfoRecord } from \"./DisplayInfoRecord\";\n",
                "export type { DisplayTargetRecord } from \"./DisplayTargetRecord\";\n",
                "export type { EmbeddedKeyEffectRecord } from \"./EmbeddedKeyEffectRecord\";\n",
                "export type { EmbeddedKeyTransitionRecord } from \"./EmbeddedKeyTransitionRecord\";\n",
                "export type { EmbeddedLaunchResultRecord } from \"./EmbeddedLaunchResultRecord\";\n",
                "export type { EmbeddedLaunchTargetRecord } from \"./EmbeddedLaunchTargetRecord\";\n",
                "export type { EmbeddedRoleLoadEffectRecord } from \"./EmbeddedRoleLoadEffectRecord\";\n",
                "export type { EmbeddedRoleViewEffectRecord } from \"./EmbeddedRoleViewEffectRecord\";\n",
                "export type { EmbeddedTabEffectRecord } from \"./EmbeddedTabEffectRecord\";\n",
                "export type { EngineCapabilitySnapshotRecord } from \"./EngineCapabilitySnapshotRecord\";\n",
                "export type { EngineCapabilityStatus } from \"./EngineCapabilityStatus\";\n",
                "export type { EngineCompatibilityCacheKeyRecord } from \"./EngineCompatibilityCacheKeyRecord\";\n",
                "export type { EngineCompatibilityCacheRecord } from \"./EngineCompatibilityCacheRecord\";\n",
                "export type { SystemWebViewIssueReason } from \"./SystemWebViewIssueReason\";\n",
                "export type { GameBrowserSettingsRecord } from \"./GameBrowserSettingsRecord\";\n",
                "export type { GameCreateInputRecord } from \"./GameCreateInputRecord\";\n",
                "export type { GameCreateRequest } from \"./GameCreateRequest\";\n",
                "export type { GameUpdateInputRecord } from \"./GameUpdateInputRecord\";\n",
                "export type { GameUpdateRequest } from \"./GameUpdateRequest\";\n",
                "export type { GameWindowCreateInputRecord } from \"./GameWindowCreateInputRecord\";\n",
                "export type { GameWindowPlacementRecord } from \"./GameWindowPlacementRecord\";\n",
                "export type { GameWindowRoleViewRecord } from \"./GameWindowRoleViewRecord\";\n",
                "export type { GameWindowTabRecord } from \"./GameWindowTabRecord\";\n",
                "export type { GameWindowUpdateInputRecord } from \"./GameWindowUpdateInputRecord\";\n",
                "export type { GraphicsDeviceDiagnosticsRecord } from \"./GraphicsDeviceDiagnosticsRecord\";\n",
                "export type { GraphicsDiagnosticsRecord } from \"./GraphicsDiagnosticsRecord\";\n",
                "export type { LayoutBounds } from \"./LayoutBounds\";\n",
                "export type { LayoutDividerBounds } from \"./LayoutDividerBounds\";\n",
                "export type { LayoutDividerInput } from \"./LayoutDividerInput\";\n",
                "export type { LayoutRect } from \"./LayoutRect\";\n",
                "export type { LayoutRoleBounds } from \"./LayoutRoleBounds\";\n",
                "export type { LayoutRoleInput } from \"./LayoutRoleInput\";\n",
                "export type { LegalAcceptanceRecord } from \"./LegalAcceptanceRecord\";\n",
                "export type { LegalAcceptDocumentsInputRecord } from \"./LegalAcceptDocumentsInputRecord\";\n",
                "export type { LegalAcceptanceStatusRecord } from \"./LegalAcceptanceStatusRecord\";\n",
                "export type { LegalDocumentVersionsRecord } from \"./LegalDocumentVersionsRecord\";\n",
                "export type { LegacySessionRestoreRecord } from \"./LegacySessionRestoreRecord\";\n",
                "export type { LocalStorageSyncRoleEffectRecord } from \"./LocalStorageSyncRoleEffectRecord\";\n",
                "export type { LocalStorageSyncSourceEffectRecord } from \"./LocalStorageSyncSourceEffectRecord\";\n",
                "export type { LogEntry } from \"./LogEntry\";\n",
                "export type { LogErrorDetails } from \"./LogErrorDetails\";\n",
                "export type { LogCaptureRecord } from \"./LogCaptureRecord\";\n",
                "export type { LogLevel } from \"./LogLevel\";\n",
                "export type { LogPageRecord } from \"./LogPageRecord\";\n",
                "export type { LogQuery } from \"./LogQuery\";\n",
                "export type { LogSource } from \"./LogSource\";\n",
                "export type { LogStorageStatusRecord } from \"./LogStorageStatusRecord\";\n",
                "export type { MacroBadgePositionRecord } from \"./MacroBadgePositionRecord\";\n",
                "export type { MacroCoordinateRecord } from \"./MacroCoordinateRecord\";\n",
                "export type { MacroCreateInputRecord } from \"./MacroCreateInputRecord\";\n",
                "export type { MacroCreateRequest } from \"./MacroCreateRequest\";\n",
                "export type { MacroDefinition } from \"./MacroDefinition\";\n",
                "export type { MacroInvocationRequest } from \"./MacroInvocationRequest\";\n",
                "export type { MacroLastClick } from \"./MacroLastClick\";\n",
                "export type { MacroOverlayRequestRecord } from \"./MacroOverlayRequestRecord\";\n",
                "export type { MacroOverlayStartSummaryRecord } from \"./MacroOverlayStartSummaryRecord\";\n",
                "export type { MacroOverlayViewModelRecord } from \"./MacroOverlayViewModelRecord\";\n",
                "export type { MacroPressInvocationRequest } from \"./MacroPressInvocationRequest\";\n",
                "export type { MacroPressRequest } from \"./MacroPressRequest\";\n",
                "export type { MacroReleaseRequest } from \"./MacroReleaseRequest\";\n",
                "export type { MacroRepeat } from \"./MacroRepeat\";\n",
                "export type { MacroRunStatus } from \"./MacroRunStatus\";\n",
                "export type { MacroRuntimeSettings } from \"./MacroRuntimeSettings\";\n",
                "export type { MacroSettingsRecord } from \"./MacroSettingsRecord\";\n",
                "export type { MacroStartRequest } from \"./MacroStartRequest\";\n",
                "export type { MacroStepDefinition } from \"./MacroStepDefinition\";\n",
                "export type { MacroStepInputRecord } from \"./MacroStepInputRecord\";\n",
                "export type { MacroTrigger } from \"./MacroTrigger\";\n",
                "export type { MacroUpdateInputRecord } from \"./MacroUpdateInputRecord\";\n",
                "export type { MacroUpdateRequest } from \"./MacroUpdateRequest\";\n",
                "export type { OperationCancelResultRecord } from \"./OperationCancelResultRecord\";\n",
                "export type { PortableDataRecord } from \"./PortableDataRecord\";\n",
                "export type { PortableDataSelectionRecord } from \"./PortableDataSelectionRecord\";\n",
                "export type { PortableExportResultRecord } from \"./PortableExportResultRecord\";\n",
                "export type { PortableGameRecord } from \"./PortableGameRecord\";\n",
                "export type { PortableGameWindowRecord } from \"./PortableGameWindowRecord\";\n",
                "export type { PortableImportOperationSummaryRecord } from \"./PortableImportOperationSummaryRecord\";\n",
                "export type { PortableImportOperationsRecord } from \"./PortableImportOperationsRecord\";\n",
                "export type { PortableImportPreviewRecord } from \"./PortableImportPreviewRecord\";\n",
                "export type { PortableImportResultRecord } from \"./PortableImportResultRecord\";\n",
                "export type { PortableImportWarningRecord } from \"./PortableImportWarningRecord\";\n",
                "export type { PortableLaunchWorkspaceRecord } from \"./PortableLaunchWorkspaceRecord\";\n",
                "export type { PortableMacroConflictCandidateRecord } from \"./PortableMacroConflictCandidateRecord\";\n",
                "export type { PortableMacroConflictRecord } from \"./PortableMacroConflictRecord\";\n",
                "export type { PortableMacroConflictResolutionRecord } from \"./PortableMacroConflictResolutionRecord\";\n",
                "export type { PortableMacroRecord } from \"./PortableMacroRecord\";\n",
                "export type { PortablePreferencesRecord } from \"./PortablePreferencesRecord\";\n",
                "export type { PortableRoleRecord } from \"./PortableRoleRecord\";\n",
                "export type { PerformanceTelemetryRecord } from \"./PerformanceTelemetryRecord\";\n",
                "export type { ResolvedBrowserEngine } from \"./ResolvedBrowserEngine\";\n",
                "export type { RoleCreateInputRecord } from \"./RoleCreateInputRecord\";\n",
                "export type { RoleCreateRequest } from \"./RoleCreateRequest\";\n",
                "export type { RoleGameAssignmentRecord } from \"./RoleGameAssignmentRecord\";\n",
                "export type { RolePathsRecord } from \"./RolePathsRecord\";\n",
                "export type { RoleUpdateInputRecord } from \"./RoleUpdateInputRecord\";\n",
                "export type { RoleUpdateRequest } from \"./RoleUpdateRequest\";\n",
                "export type { RuntimeRestoreSessionRecord } from \"./RuntimeRestoreSessionRecord\";\n",
                "export type { RuntimeRestoreTabRecord } from \"./RuntimeRestoreTabRecord\";\n",
                "export type { RuntimeRestoreWindowRecord } from \"./RuntimeRestoreWindowRecord\";\n",
                "export type { RuntimeWindowPreferencesRecord } from \"./RuntimeWindowPreferencesRecord\";\n",
                "export type { StateCollection } from \"./StateCollection\";\n",
                "export type { StateCompatibilityLoadRecord } from \"./StateCompatibilityLoadRecord\";\n",
                "export type { StateCompatibilityObservationsRecord } from \"./StateCompatibilityObservationsRecord\";\n",
                "export type { StateCompatibilityRecommendationRecord } from \"./StateCompatibilityRecommendationRecord\";\n",
                "export type { StateCompatibilityReportRecord } from \"./StateCompatibilityReportRecord\";\n",
                "export type { StateGameRecord } from \"./StateGameRecord\";\n",
                "export type { StateGameWindowRecord } from \"./StateGameWindowRecord\";\n",
                "export type { StateLaunchWorkspaceRecord } from \"./StateLaunchWorkspaceRecord\";\n",
                "export type { StateMacroRecord } from \"./StateMacroRecord\";\n",
                "export type { StateNormalizedRectRecord } from \"./StateNormalizedRectRecord\";\n",
                "export type { StatePixelBoundsRecord } from \"./StatePixelBoundsRecord\";\n",
                "export type { StateResolutionRecord } from \"./StateResolutionRecord\";\n",
                "export type { StateRoleRecord } from \"./StateRoleRecord\";\n",
                "export type { StateWebGraphicsRecord } from \"./StateWebGraphicsRecord\";\n",
                "export type { StateWorkspaceSlotRecord } from \"./StateWorkspaceSlotRecord\";\n",
                "export type { SystemFontFamilyRecord } from \"./SystemFontFamilyRecord\";\n",
                "export type { SystemWebViewProbeRecord } from \"./SystemWebViewProbeRecord\";\n",
                "export type { SystemWebViewRuntimeRegistrationRecord } from \"./SystemWebViewRuntimeRegistrationRecord\";\n",
                "export type { TelemetryMetric } from \"./TelemetryMetric\";\n",
                "export type { TelemetrySampleRecord } from \"./TelemetrySampleRecord\";\n",
                "export type { LatencySummaryRecord } from \"./LatencySummaryRecord\";\n",
                "export type { WorkspaceAppearanceSettingsRecord } from \"./WorkspaceAppearanceSettingsRecord\";\n",
                "export type { WorkspaceCreateInputRecord } from \"./WorkspaceCreateInputRecord\";\n",
                "export type { WorkspaceCreateRequest } from \"./WorkspaceCreateRequest\";\n",
                "export type { WorkspaceDividerDescriptor } from \"./WorkspaceDividerDescriptor\";\n",
                "export type { WorkspaceDividerResizeInput } from \"./WorkspaceDividerResizeInput\";\n",
                "export type { WorkspaceDividerResizeOutput } from \"./WorkspaceDividerResizeOutput\";\n",
                "export type { WorkspaceLayoutInput } from \"./WorkspaceLayoutInput\";\n",
                "export type { WorkspaceLayoutOutput } from \"./WorkspaceLayoutOutput\";\n",
                "export type { WorkspaceSlotInputRecord } from \"./WorkspaceSlotInputRecord\";\n",
                "export type { WorkspaceSlotRequest } from \"./WorkspaceSlotRequest\";\n",
                "export type { WorkspaceUpdateInputRecord } from \"./WorkspaceUpdateInputRecord\";\n",
                "export type { WorkspaceUpdateRequest } from \"./WorkspaceUpdateRequest\";\n",
                "export type { WindowsGraphicsEventCollectionRecord } from \"./WindowsGraphicsEventCollectionRecord\";\n",
                "export type { WindowsGraphicsEventRecord } from \"./WindowsGraphicsEventRecord\";\n",
            ),
        )
        .unwrap();
        fs::write(
            PathBuf::from(env!("CARGO_MANIFEST_DIR"))
                .join("../../src/shared/generated/CoreCommandResultMap.ts"),
            concat!(
                "// Generated by rion-core. Do not edit by hand.\n",
                "import type { BrowserRoleStatusRecord } from \"./BrowserRoleStatusRecord\";\n",
                "import type { BrowserRuntimeSnapshot } from \"./BrowserRuntimeSnapshot\";\n",
                "import type { BrowserWorkspaceStatusRecord } from \"./BrowserWorkspaceStatusRecord\";\n",
                "import type { BulkDeleteResultRecord } from \"./BulkDeleteResultRecord\";\n",
                "import type { ChromeProfileImportPreviewRecord } from \"./ChromeProfileImportPreviewRecord\";\n",
                "import type { ChromeProfileImportResultRecord } from \"./ChromeProfileImportResultRecord\";\n",
                "import type { CompatibilityRunStatusRecord } from \"./CompatibilityRunStatusRecord\";\n",
                "import type { CoreCommand } from \"./CoreCommand\";\n",
                "import type { CoreEffectMetricsRecord } from \"./CoreEffectMetricsRecord\";\n",
                "import type { CoreStateSnapshotRecord } from \"./CoreStateSnapshotRecord\";\n",
                "import type { DiagnosticExportResultRecord } from \"./DiagnosticExportResultRecord\";\n",
                "import type { EmbeddedKeyTransitionRecord } from \"./EmbeddedKeyTransitionRecord\";\n",
                "import type { EmbeddedLaunchResultRecord } from \"./EmbeddedLaunchResultRecord\";\n",
                "import type { EngineCompatibilityCacheRecord } from \"./EngineCompatibilityCacheRecord\";\n",
                "import type { GameBrowserSettingsRecord } from \"./GameBrowserSettingsRecord\";\n",
                "import type { GraphicsDiagnosticsRecord } from \"./GraphicsDiagnosticsRecord\";\n",
                "import type { LegalAcceptanceStatusRecord } from \"./LegalAcceptanceStatusRecord\";\n",
                "import type { LayoutRect } from \"./LayoutRect\";\n",
                "import type { LogPageRecord } from \"./LogPageRecord\";\n",
                "import type { LogStorageStatusRecord } from \"./LogStorageStatusRecord\";\n",
                "import type { MacroOverlayViewModelRecord } from \"./MacroOverlayViewModelRecord\";\n",
                "import type { MacroRunStatus } from \"./MacroRunStatus\";\n",
                "import type { MacroSettingsRecord } from \"./MacroSettingsRecord\";\n",
                "import type { OperationCancelResultRecord } from \"./OperationCancelResultRecord\";\n",
                "import type { PerformanceTelemetryRecord } from \"./PerformanceTelemetryRecord\";\n",
                "import type { PortableExportResultRecord } from \"./PortableExportResultRecord\";\n",
                "import type { PortableImportPreviewRecord } from \"./PortableImportPreviewRecord\";\n",
                "import type { PortableImportResultRecord } from \"./PortableImportResultRecord\";\n",
                "import type { RolePathsRecord } from \"./RolePathsRecord\";\n",
                "import type { RuntimeWindowPreferencesRecord } from \"./RuntimeWindowPreferencesRecord\";\n",
                "import type { RuntimeRestoreSessionRecord } from \"./RuntimeRestoreSessionRecord\";\n",
                "import type { StateCompatibilityReportRecord } from \"./StateCompatibilityReportRecord\";\n",
                "import type { StateGameRecord } from \"./StateGameRecord\";\n",
                "import type { StateGameWindowRecord } from \"./StateGameWindowRecord\";\n",
                "import type { StateLaunchWorkspaceRecord } from \"./StateLaunchWorkspaceRecord\";\n",
                "import type { StateMacroRecord } from \"./StateMacroRecord\";\n",
                "import type { StateRoleRecord } from \"./StateRoleRecord\";\n",
                "import type { SystemFontFamilyRecord } from \"./SystemFontFamilyRecord\";\n",
                "import type { SystemWebViewProbeRecord } from \"./SystemWebViewProbeRecord\";\n",
                "import type { SystemWebViewRuntimeRegistrationRecord } from \"./SystemWebViewRuntimeRegistrationRecord\";\n",
                "import type { WindowsGraphicsEventCollectionRecord } from \"./WindowsGraphicsEventCollectionRecord\";\n\n",
                "import type { WorkspaceDividerDescriptor } from \"./WorkspaceDividerDescriptor\";\n",
                "import type { WorkspaceDividerResizeOutput } from \"./WorkspaceDividerResizeOutput\";\n\n",
                "import type { WorkspaceLayoutOutput } from \"./WorkspaceLayoutOutput\";\n",
                "export type CoreJsonValue = null | boolean | number | string | CoreJsonValue[] | { [key: string]: CoreJsonValue };\n\n",
                "type DefaultCoreCommandResultMap = { [K in CoreCommand[\"type\"]]: CoreJsonValue };\n\n",
                "type TypedCoreCommandResultMap = {\n",
                "  systemWebViewProbe: SystemWebViewProbeRecord;\n",
                "  systemWebViewRuntimeRegister: SystemWebViewRuntimeRegistrationRecord;\n",
                "  stateSnapshot: CoreStateSnapshotRecord;\n",
                "  gamesList: StateGameRecord[];\n",
                "  gameGet: StateGameRecord;\n",
                "  gameCreate: StateGameRecord;\n",
                "  gameUpdate: StateGameRecord;\n",
                "  gameResetBuiltin: StateGameRecord;\n",
                "  gamesDelete: BulkDeleteResultRecord;\n",
                "  rolesList: StateRoleRecord[];\n",
                "  roleGet: StateRoleRecord;\n",
                "  roleCreate: StateRoleRecord;\n",
                "  roleUpdate: StateRoleRecord;\n",
                "  roleReorder: StateRoleRecord[];\n",
                "  roleBrowserDataClear: StateRoleRecord;\n",
                "  roleBrowserDirectoryEnsure: RolePathsRecord;\n",
                "  roleBrowserDirectoryReset: RolePathsRecord;\n",
                "  rolePathsResolve: RolePathsRecord;\n",
                "  roleAssignGameIds: StateRoleRecord[];\n",
                "  rolesDelete: BulkDeleteResultRecord;\n",
                "  chromeProfileDefaultPath: string;\n",
                "  chromeProfilePreview: ChromeProfileImportPreviewRecord;\n",
                "  chromeProfileRefresh: ChromeProfileImportPreviewRecord;\n",
                "  chromeProfileRequestQuit: ChromeProfileImportPreviewRecord;\n",
                "  chromeProfileApply: ChromeProfileImportResultRecord;\n",
                "  workspacesList: StateLaunchWorkspaceRecord[];\n",
                "  workspaceGet: StateLaunchWorkspaceRecord;\n",
                "  workspaceCreate: StateLaunchWorkspaceRecord;\n",
                "  workspaceUpdate: StateLaunchWorkspaceRecord;\n",
                "  workspaceReorder: StateLaunchWorkspaceRecord[];\n",
                "  workspaceSetRoleBrowserZoom: StateLaunchWorkspaceRecord | null;\n",
                "  workspacesDelete: BulkDeleteResultRecord;\n",
                "  gameWindowsList: StateGameWindowRecord[];\n",
                "  gameWindowGet: StateGameWindowRecord;\n",
                "  gameWindowCreate: StateGameWindowRecord;\n",
                "  gameWindowUpdate: StateGameWindowRecord;\n",
                "  gameWindowReorder: StateGameWindowRecord[];\n",
                "  macrosList: StateMacroRecord[];\n",
                "  macroGet: StateMacroRecord;\n",
                "  macroCreate: StateMacroRecord;\n",
                "  macroUpdate: StateMacroRecord;\n",
                "  macrosDelete: BulkDeleteResultRecord;\n",
                "  compatibilityStatuses: CompatibilityRunStatusRecord[];\n",
                "  compatibilityReportsCurrent: StateCompatibilityReportRecord[];\n",
                "  compatibilityRun: StateCompatibilityReportRecord;\n",
                "  gameBrowserSettingsGet: GameBrowserSettingsRecord;\n",
                "  gameBrowserSettingsReplace: GameBrowserSettingsRecord;\n",
                "  engineCompatibilityCacheGet: EngineCompatibilityCacheRecord | null;\n",
                "  engineCompatibilityCachePut: EngineCompatibilityCacheRecord;\n",
                "  engineCompatibilityCacheDeleteGame: { deletedCount: number };\n",
                "  macroSettingsGet: MacroSettingsRecord;\n",
                "  macroSettingsReplace: MacroSettingsRecord;\n",
                "  runtimeWindowPreferencesGet: RuntimeWindowPreferencesRecord;\n",
                "  runtimeWindowPreferencesReplace: RuntimeWindowPreferencesRecord;\n",
                "  runtimeRestoreSessionGet: RuntimeRestoreSessionRecord;\n",
                "  runtimeRestoreSessionReplace: RuntimeRestoreSessionRecord;\n",
                "  legalAcceptanceStatus: LegalAcceptanceStatusRecord;\n",
                "  legalAcceptanceAccept: LegalAcceptanceStatusRecord;\n",
                "  systemFontsList: SystemFontFamilyRecord[];\n",
                "  portableExport: PortableExportResultRecord | null;\n",
                "  portableExportTo: PortableExportResultRecord;\n",
                "  portablePreview: PortableImportPreviewRecord | null;\n",
                "  portablePreviewFile: PortableImportPreviewRecord | null;\n",
                "  portableApply: PortableImportResultRecord;\n",
                "  macroStart: MacroRunStatus[];\n",
                "  macroPress: MacroRunStatus[];\n",
                "  macroStatuses: MacroRunStatus[];\n",
                "  layoutResolve: WorkspaceLayoutOutput;\n",
                "  layoutNormalizeRects: LayoutRect[];\n",
                "  layoutCreateDividers: WorkspaceDividerDescriptor[];\n",
                "  layoutResizeDivider: WorkspaceDividerResizeOutput;\n",
                "  layoutAdaptiveZoom: number;\n",
                "  embeddedKeyPrepare: EmbeddedKeyTransitionRecord;\n",
                "  embeddedKeysReassert: EmbeddedKeyTransitionRecord;\n",
                "  embeddedKeysHeld: boolean;\n",
                "  operationCancel: OperationCancelResultRecord;\n",
                "  coreEffectMetrics: CoreEffectMetricsRecord;\n",
                "  embeddedRoleLaunch: EmbeddedLaunchResultRecord[];\n",
                "  embeddedWorkspaceLaunch: EmbeddedLaunchResultRecord[];\n",
                "  embeddedSystemSurfaceFailed: BrowserRoleStatusRecord[];\n",
                "  embeddedSystemSurfaceRecovered: BrowserRoleStatusRecord[];\n",
                "  embeddedWindowsShow: BrowserRuntimeSnapshot;\n",
                "  embeddedTabActivate: BrowserRuntimeSnapshot;\n",
                "  embeddedTabActivateAdjacent: BrowserRuntimeSnapshot;\n",
                "  embeddedTabHide: BrowserRuntimeSnapshot;\n",
                "  embeddedTabReorder: BrowserRuntimeSnapshot;\n",
                "  embeddedTabMove: BrowserRuntimeSnapshot;\n",
                "  browserRoleLaunch: BrowserRoleStatusRecord[];\n",
                "  browserWorkspaceLaunch: BrowserRoleStatusRecord[];\n",
                "  browserStatuses: BrowserRoleStatusRecord[];\n",
                "  browserWorkspaceStatuses: BrowserWorkspaceStatusRecord[];\n",
                "  browserRuntimeSnapshot: BrowserRuntimeSnapshot;\n",
                "  graphicsDiagnosticsAssemble: GraphicsDiagnosticsRecord;\n",
                "  logsQuery: LogPageRecord;\n",
                "  logsStatus: LogStorageStatusRecord;\n",
                "  diagnosticsExport: DiagnosticExportResultRecord;\n",
                "  telemetrySnapshot: PerformanceTelemetryRecord;\n",
                "  overlayRequest: MacroOverlayViewModelRecord;\n",
                "  windowsGraphicsEventsCollect: WindowsGraphicsEventCollectionRecord;\n",
                "};\n\n",
                "export type CoreCommandResultMap = Omit<DefaultCoreCommandResultMap, keyof TypedCoreCommandResultMap> & TypedCoreCommandResultMap;\n\n",
                "export type CoreCommandResult<C extends CoreCommand> = CoreCommandResultMap[C[\"type\"]];\n",
            ),
        )
        .unwrap();
    }
}
