mod app;
mod cdn;
mod database;
mod error;
mod external_chrome;
mod macro_graph;
mod model;
mod pressure;
mod resource;
mod scheduler;

pub use app::AppCore;
pub use error::{CoreError, CoreErrorPayload, CoreResult};
pub use external_chrome::{CdpEvent, ExternalChromeCdpSession};
pub use model::{
    AppCoreOptions, BrowserAction, BrowserActionRequest, BrowserActionResult, CdnRule, CoreCommand,
    CoreEvent, LogEntry, LogQuery, PressureLevel, ResourcePolicyDecision, ResourcePolicyInput,
    SystemPressureSnapshot,
};

pub const CORE_VERSION: &str = env!("CARGO_PKG_VERSION");

#[cfg(test)]
mod generated_contract_tests {
    use std::{fs, path::PathBuf};

    #[test]
    fn export_bindings_index() {
        let path =
            PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../src/shared/generated/index.ts");
        fs::write(
            path,
            concat!(
                "// Generated by ts-rs from crates/rion-core. Do not edit exported type files by hand.\n",
                "export type { BrowserActionRequest } from \"./BrowserActionRequest\";\n",
                "export type { BrowserAction } from \"./BrowserAction\";\n",
                "export type { BrowserActionResult } from \"./BrowserActionResult\";\n",
                "export type { CdnRule } from \"./CdnRule\";\n",
                "export type { CoreErrorPayload } from \"./CoreErrorPayload\";\n",
                "export type { CoreEvent } from \"./CoreEvent\";\n",
                "export type { PressureLevel } from \"./PressureLevel\";\n",
                "export type { ResourcePolicyDecision } from \"./ResourcePolicyDecision\";\n",
                "export type { ResourcePolicyInput } from \"./ResourcePolicyInput\";\n",
                "export type { SystemPressureSnapshot } from \"./SystemPressureSnapshot\";\n",
            ),
        )
        .unwrap();
    }
}
